services:
  frontend:
    build: .
    container_name: mitr-frontend-api
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    networks:
      - mitr-network
