import {
  OT_METHOD,
  OT_TYPE,
  PENALTY_METHOD,
  PENALTY_TYPE,
  SALARY_FIELD_DEFINATION_TYPE,
} from "./types/enum/enum";
import { PayrollRecordSummary } from "./types/payrollPeriodSummary";
import XLSX from "xlsx-js-style";

const fs = require("fs");

const data: PayrollRecordSummary[] = [
  {
    id: 121,
    baseSalary: 0.0,
    employee: {
      id: 5,
      firstName: "ฮานาฟี",
      lastName: "เจะโดง",
      nickName: "ฟี",
      branch: "ปากเกร็ด",
      branchEng: "Pakkret",
    },
    totals: {
      totalSalaryIncome: 0,
      totalSalaryDeduction: 0,
      totalOT: 0,
      totalPenalty: 0,
      totalEarning: 0,
      totalDeduction: 0,
      net: 0,
    },
    fields: [
      {
        id: 644,
        payrollRecordId: 121,
        name: "เบี้ยขยัน",
        nameEng: "Digital allowance",
        type: SALARY_FIELD_DEFINATION_TYPE.INCOME,
        formular: null,
        amount: "0.00",
        createdAt: new Date(new Date("2025-12-04T09:59:52.000Z")),
      },
      {
        id: 645,
        payrollRecordId: 121,
        name: "ประกันสังคม",
        nameEng: "ประกันสังคม",
        type: SALARY_FIELD_DEFINATION_TYPE.DEDUCTION,
        formular: null,
        amount: "0.00",
        createdAt: new Date("2025-12-04T09:59:52.000Z"),
      },
      {
        id: 646,
        payrollRecordId: 121,
        name: "ค่าตำแหน่ง",
        nameEng: "ค่าตำแหน่ง",
        type: SALARY_FIELD_DEFINATION_TYPE.INCOME,
        formular: null,
        amount: "0.00",
        createdAt: new Date("2025-12-04T09:59:52.000Z"),
      },
      {
        id: 647,
        payrollRecordId: 121,
        name: "เบิก",
        nameEng: "เบิก",
        type: SALARY_FIELD_DEFINATION_TYPE.DEDUCTION,
        formular: null,
        amount: "0.00",
        createdAt: new Date("2025-12-04T09:59:52.000Z"),
      },
      {
        id: 648,
        payrollRecordId: 121,
        name: "ยอดจ่ายเงินกู้",
        nameEng: "ยอดจ่ายเงินกู้",
        type: SALARY_FIELD_DEFINATION_TYPE.DEDUCTION,
        formular: null,
        amount: "0.00",
        createdAt: new Date("2025-12-04T09:59:52.000Z"),
      },
      {
        id: 649,
        payrollRecordId: 121,
        name: "สวัสดิการอื่นๆ",
        nameEng: "สวัสดิการอื่นๆ",
        type: SALARY_FIELD_DEFINATION_TYPE.INCOME,
        formular: null,
        amount: "0.00",
        createdAt: new Date("2025-12-04T09:59:52.000Z"),
      },
      {
        id: 650,
        payrollRecordId: 121,
        name: "หนี้",
        nameEng: "หนี้",
        type: SALARY_FIELD_DEFINATION_TYPE.DEDUCTION,
        formular: null,
        amount: "0.00",
        createdAt: new Date("2025-12-04T09:59:52.000Z"),
      },
      {
        id: 651,
        payrollRecordId: 121,
        name: "ยอดเป้า",
        nameEng: "ยอดเป้า",
        type: SALARY_FIELD_DEFINATION_TYPE.INCOME,
        formular: null,
        amount: "0.00",
        createdAt: new Date("2025-12-04T09:59:52.000Z"),
      },
      {
        id: 652,
        payrollRecordId: 121,
        name: "โบนัส",
        nameEng: "โบนัส",
        type: SALARY_FIELD_DEFINATION_TYPE.INCOME,
        formular: null,
        amount: "0.00",
        createdAt: new Date("2025-12-04T09:59:52.000Z"),
      },
      {
        id: 653,
        payrollRecordId: 121,
        name: "เงินกู้ค้าง",
        nameEng: "Remainning lone",
        type: SALARY_FIELD_DEFINATION_TYPE.NON_CALCULATED,
        formular: null,
        amount: "0.00",
        createdAt: new Date("2025-12-04T09:59:52.000Z"),
      },
    ],
    ot: [
      {
        id: 205,
        payrollRecordId: 121,
        name: "OT (วัน)",
        nameEng: "OT (วัน)",
        type: OT_TYPE.BASEDONSALARY,
        method: OT_METHOD.DAILY,
        rate: "1.00",
        rateOfPay: "0.00",
        value: "0.00",
        amount: "0.00",
        createdAt: new Date("2025-12-04T09:59:52.000Z"),
      },
      {
        id: 206,
        payrollRecordId: 121,
        name: "OT (ชั่วโมง)",
        nameEng: "OT (ชั่วโมง)",
        type: OT_TYPE.BASEDONSALARY,
        method: OT_METHOD.HOURLY,
        rate: "1.50",
        rateOfPay: "0.00",
        value: "0.00",
        amount: "0.00",
        createdAt: new Date("2025-12-04T09:59:52.000Z"),
      },
      {
        id: 207,
        payrollRecordId: 121,
        name: "OT (นักขัตฤกษ์)",
        nameEng: "OT (นักขัตฤกษ์)",
        type: OT_TYPE.BASEDONSALARY,
        method: OT_METHOD.DAILY,
        rate: "3.00",
        rateOfPay: "0.00",
        value: "0.00",
        amount: "0.00",
        createdAt: new Date("2025-12-04T09:59:52.000Z"),
      },
    ],
    penalties: [
      {
        id: 271,
        payrollRecordId: 121,
        name: "สาย (นาที)",
        nameEng: "สาย (นาที)",
        type: PENALTY_TYPE.CONSTANT,
        method: PENALTY_METHOD.PERMINUTE,
        rateOfPay: "1.00",
        value: "0.00",
        amount: "0.00",
        createdAt: new Date("2025-12-04T09:59:52.000Z"),
      },
      {
        id: 272,
        payrollRecordId: 121,
        name: "ขาด (วัน)",
        nameEng: "ขาด (วัน)",
        type: PENALTY_TYPE.BASEDONSALARY,
        method: PENALTY_METHOD.DAILY,
        rateOfPay: "0.00",
        value: "0.00",
        amount: "0.00",
        createdAt: new Date("2025-12-04T09:59:52.000Z"),
      },
      {
        id: 273,
        payrollRecordId: 121,
        name: "ลาป่วย (วัน)",
        nameEng: "ลาป่วย (วัน)",
        type: PENALTY_TYPE.CONSTANT,
        method: PENALTY_METHOD.DAILY,
        rateOfPay: "0.00",
        value: "0.00",
        amount: "0.00",
        createdAt: new Date("2025-12-04T09:59:52.000Z"),
      },
      {
        id: 274,
        payrollRecordId: 121,
        name: "ลากิจ (วัน)",
        nameEng: "ลากิจ (วัน)",
        type: PENALTY_TYPE.BASEDONSALARY,
        method: PENALTY_METHOD.DAILY,
        rateOfPay: "0.00",
        value: "0.00",
        amount: "0.00",
        createdAt: new Date("2025-12-04T09:59:52.000Z"),
      },
    ],
  },
];


exportPayroll(data);
