import type { Metadata } from "next";
import { Sarabun } from "next/font/google";
import "./globals.css";
import ShopSidebar from "./components/ShopSidebar";
import DashboardSidebar from "./components/DashboardSidebar/DashboardSidebar";

const sarabun = Sarabun({
  subsets: ["thai", "latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${sarabun.className} antialiased flex`}>
        <ShopSidebar />
        <DashboardSidebar />
        {children}
      </body>
    </html>
  );
}
