import type { Metadata } from "next";
import { Sarabun } from "next/font/google";
import "./globals.css";
import DashboardSidebar from "./components/DashboardSidebar/DashboardSidebar";
import Providers from "./providers";
import { signIn } from "next-auth/react";
import { redirect } from "next/navigation";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/route";

const sarabun = Sarabun({
  subsets: ["thai", "latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body className={`${sarabun.className} antialiased flex`}>
        <Providers session={session}>
          {/* <ShopSidebar /> */}
          <DashboardSidebar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
