export enum COMPEN_FIELD_DEFINATION_TYPE {
  INCOME = "INCOME",
  DEDUCTION = "DEDUCTION",
  NON_CALCULATED = "NON_CALCULATED",
}

export enum COMPEN_FIELD_STATUS {
  ACTIVE = "ACTIVE",
  INACTIVE = "INACTIVE",
}
