export enum GENDER {
  MALE='male',
  FEMALE='female',
  OTHER= 'other'
} 

export enum EMPLOYEE_STATUS {
  ACTIVE= 'ACTIVE',
  INACTIVE= 'INACTIVE',
  PARTTIME= 'PARTTIME'
} 

export enum PAY_PERIOD_STATUS {
  DRAFT= 'DRAFT',
  FINALIZED='FINALIZED',
  PAID= 'PAID',
} 

export enum OT_TYPE {
  CONSTANT= 'CONSTANT',
  BASEDONSALARY='BASEDONSALARY'
} 

export enum OT_METHOD {
  DAILY= 'DAILY',
  HOURLY='HOURLY'
} 

export enum PENALTY_TYPE {
  CONSTANT= 'CONSTANT',
  BASEDONSALARY='BASEDONSALARY'
} 

export enum PENALTY_METHOD {
  PERMINUTE= 'PERMINUTE',
  DAILY= 'DAILY',
  HOURLY='HOURLY'
} 

export enum SALARY_FIELD_DEFINATION_TYPE {
  INCOME= 'INCOME',
  DEDUCTION='DEDUCTION',
} 