export enum GENDER {
  MALE = "male",
  FEMALE = "female",
  OTHER = "other",
}

export enum EMPLOYEE_STATUS {
  ACTIVE = "ACTIVE",
  INACTIVE = "INACTIVE",
  PARTTIME = "PARTTIME",
}

export enum PAY_PERIOD_STATUS {
  DRAFT = "DRAFT",
  FINALIZED = "FINALIZED",
  PAID = "PAID",
}

export enum OT_TYPE {
  CONSTANT = "CONSTANT",
  BASEDONSALARY = "BASEDONSALARY",
}

export enum OT_METHOD {
  DAILY = "DAILY",
  HOURLY = "HOURLY",
}

export enum PENALTY_TYPE {
  CONSTANT = "CONSTANT",
  BASEDONSALARY = "BASEDONSALARY",
}

export enum PENALTY_METHOD {
  PERMINUTE = "PERMINUTE",
  DAILY = "DAILY",
  HOURLY = "HOURLY",
}

export enum SALARY_FIELD_DEFINATION_TYPE {
  INCOME = "INCOME",
  DEDUCTION = "DEDUCTION",
  NON_CALCULATED = "NON_CALCULATED",
}

export enum SALARY_FIELD_STATUS {
  ACTIVE = "ACTIVE",
  INACTIVE = "INACTIVE",
}

export enum INVITATION_STATUS {
  PENDING = "PENDING",
  ACCEPTED = "ACCEPTED",
  REVOKE = "REVOKE",
}

export enum PAYROLL_PROBLEM {
  WARNNING = "WARNNING",
  CRITICAL = "CRITICAL",
}

export enum PAYROLL_PROBLEM_CODE {
  NO_EMPLOYEE = "NO_EMPLOYEE",
  BASE_SALARY_ZERO = "BASE_SALARY_ZERO",
  NET_NEGATIVE = "NET_NEGATIVE",
  NET_ZERO = "NET_ZERO",
  DEDUCTION_EXCEED_EARNING = "DEDUCTION_EXCEED_EARNING",
  NET_MISMATCH = "NET_MISMATCH",
  OT_HOURS_EXCEED_LIMIT = "OT_HOURS_EXCEED_LIMIT",
  OT_AMOUNT_MISMATCH = "OT_AMOUNT_MISMATCH",
  OT_NEGATIVE = "OT_NEGATIVE",
  PENALTY_EXCEED_GROSS = "PENALTY_EXCEED_GROSS",
  PENALTY_EXCEED_30_PERCENT = "PENALTY_EXCEED_30_PERCENT",
  PENALTY_NEGATIVE = "PENALTY_NEGATIVE",
  PENALTY_MISMATCH = "PENALTY_MISMATCH",
}
