import { EmployeeSnapshotDTO } from "../type.entry";

export type ValidationResultDTO = {
  type: ISSUE_TYPE;
  code: ISSUE_CODE;
  employee: Pick<EmployeeSnapshotDTO["snapshot"], "firstName" | "lastName">;
  meta?: Record<string, any>;
};

export enum ISSUE_TYPE {
  WARNING,
  CRITICAL,
}

export enum ISSUE_CODE {
  NO_EMPLOYEE = "NO_EMPLOYEE",
  BASE_SALARY_ZERO = "BASE_SALARY_ZERO",
  NET_NEGATIVE = "NET_NEGATIVE",
  NET_ZERO = "NET_ZERO",
  DEDUCTION_EXCEED_EARNING = "DEDUCTION_EXCEED_EARNING",
  NET_MISMATCH = "NET_MISMATCH",
  OT_HOURS_EXCEED_LIMIT = "OT_HOURS_EXCEED_LIMIT",
  OT_AMOUNT_MISMATCH = "OT_AMOUNT_MISMATCH",
  OT_NEGATIVE = "OT_NEGATIVE",
  PENALTY_EXCEED_GROSS = "PENALTY_EXCEED_GROSS",
  PENALTY_EXCEED_30_PERCENT = "PENALTY_EXCEED_30_PERCENT",
  PENALTY_NEGATIVE = "PENALTY_NEGATIVE",
  PENALTY_MISMATCH = "PENALTY_MISMATCH",
}
